mentors/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.IndexPage.as_view(), name='index'),
    path('mentor_list/', views.MentorListAPI.as_view(), name='mentor_list'),
    path('mentor/<int:pk>/', views.MentorPage.as_view(), name='mentor'),
    path('mentor_api/<int:pk>/', views.MentorDetailAPI.as_view(), name='mentor_api'),
    path('course_api/<int:pk>/', views.MentorCourseListAPI.as_view(), name='course_api'),
    path('letter_list/', views.LetterListAPI.as_view(), name='letter_list'),
    path('create_letter/', views.CreateYourLetterPage.as_view(), name='create_letter'),
    path('edit_letter/<int:pk>/', views.EditYourLetterPage.as_view(), name='edit_letter'),
    path('edit_letter_api/<int:pk>/', views.EditYourLetterAPI.as_view(), name='edit_letter_api'),
    path('delete_letter/<int:pk>/', views.DeleteYourLetterPage.as_view(), name='delete_letter'),
]

my_mentors/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mentors.urls')),
    path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favoricon.ico")),),
]

mentors/models.py
# pylint: disable=E1101
from django.db import models


class MyMentor(models.Model):
    mentor_name = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    twitter_link = models.CharField(max_length=200, blank=True, null=True)
    youtube_link = models.CharField(max_length=200, blank=True, null=True)
    text_body = models.TextField(max_length=1500, blank=True, null=True)

    def __str__(self):
        return self.mentor_name


class Course(models.Model):
    mentor = models.ForeignKey(MyMentor, blank=True, null=True, on_delete=models.CASCADE)
    custom_id = models.IntegerField(blank=True, null=True)
    thumbnail = models.ImageField(max_length=255, null=True, blank=True)
    link = models.CharField(max_length=2085, null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.custom_id)


class YourLetter(models.Model):
    name = models.CharField(max_length=255, null=True)
    image = models.ImageField(max_length=255, null=False, blank=False)
    text = models.TextField(null=True, max_length=1500)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']
    

mentors/forms.py
from django.forms import ModelForm
from .models import YourLetter
from django import forms


class YourLetterForm(ModelForm):
    image = forms.ImageField(widget=forms.FileInput)
    class Meta:
        model = YourLetter
        fields = '__all__'

mentors/views.py
# pylint: disable=E1101
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404

from .models import MyMentor, YourLetter, Course
from .serializers import MyMentorSerializer, YourLetterSerializer, CourseSerializer
from .forms import YourLetterForm


class IndexPage(TemplateView):
    template_name = 'mentors/index.html'


class MentorListAPI(APIView):
    """
        retrieves all mymentors and output them
    """
    def get(self, request, format=None):
        mentors = MyMentor.objects.all()
        serializer = MyMentorSerializer(mentors, many=True)
        return Response(serializer.data)


class MentorPage(DetailView):
    model = MyMentor
    template_name = 'mentors/mentor.html'
    context_object_name = 'mentor'


class MentorDetailAPI(APIView):
    def get_object(self, pk):
        try:
            return MyMentor.objects.get(id=pk)
        except MyMentor.DoesNotExist:
            return Http404

    def get(self, request, pk, format=None):
        mentor = self.get_object(pk)
        serializer = MyMentorSerializer(mentor)
        return Response(serializer.data)


class MentorCourseListAPI(APIView):
    def get_object(self, pk):
        try:
            return MyMentor.objects.get(id=pk)
        except MyMentor.DoesNotExist:
            return Http404

    def get(self, request, pk, format=None):
        mentor = self.get_object(pk)
        course_list = mentor.course_set.all()
        serializer = CourseSerializer(course_list, many=True)
        return Response(serializer.data)


class LetterListAPI(APIView):
    """
        retrieves all youtletters and output them, or create a new yourletter
    """
    def get(self, request, format=None):
        letters = YourLetter.objects.all()
        serializer = YourLetterSerializer(letters, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = YourLetterSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateYourLetterPage(TemplateView):
    template_name = 'mentors/create_letter.html'


class EditYourLetterPage(UpdateView):
    form_class = YourLetterForm
    queryset = YourLetter.objects.all()
    template_name = 'mentors/edit_letter.html'

    def get_context_data(self, **kwargs): #throw a letter into context
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get(self.pk_url_kwarg)
        letter = YourLetter.objects.get(id=pk)
        context['letter'] = letter
        return context


class EditYourLetterAPI(APIView):
    """
        Edit and delete a yourletter instance. 
    """
    def get_object(self, pk):
        try:
            return YourLetter.objects.get(id=pk)
        except YourLetter.DoesNotExist:
            raise Http404 
             
    def put(self, request, pk, format=None):
        letter = self.get_object(pk)
        image = letter.image
        if 'image' not in request.data: #if no image set an established one
            request.data._mutable = True
            request.data['image'] = image
        serializer = YourLetterSerializer(letter, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        letter = self.get_object(pk)
        letter.delete()
        return Response('deleted')


class DeleteYourLetterPage(TemplateView):
    template_name = 'mentors/delete_letter.html'

    

mentors/templates/mentors/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/favoricon.ico' %}">

    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <!-- css -->
    <link rel="stylesheet" href="{% static 'css/mentor_style.css' %}">
    <!-- <link rel="stylesheet" href="/static/css/mentor_style.css/"> -->
</head>

<body>
    <div class="container">
        {% block content %}

        {% endblock content %}
        <br>
        <footer>Powered by Tim WD 2021.</footer>
        <br><br>
    </div>
</body>
</html>

mentors/templates/mentors/create_letter.html
{% extends 'mentors/base.html' %}
{% load static %}
{% block title %}Create Letter{% endblock title %}
{% block content %}

    <section class="cud_letter">
        <form action="" id="formCreate" class="flex fd-col ai-c">
            <div class="inputs flex fd-row">
                <label for="image" class="flex jc-fe"><i class="fas fa-user-plus fa-5x"></i></label>
                <input type="file" name="image" id="image">
                <div class="name_text flex fd-col ai-fs">
                    <input type="text" name="name" id="name" placeholder="Name..." required>
                    <textarea name="text" id="text" rows="7" placeholder="Start typing here..." required></textarea>
                </div>
            </div>
            <div class="buttons_cta">
                <a href="{% url 'index' %}" id="backbtn" class="button">Back</a>
                <input class="button" type="submit" value="Save">
            </div>
        </form>
    </section>

    <script src="{% static 'js/create_letter.js' %}"></script>

{% endblock content %}

mentors/templates/mentors/delete_letter.html
{% extends 'mentors/base.html' %}
{% load static %}
{% block title %}Delete Letter{% endblock title %}
{% block content %}

<section class="cud_letter">
    <div class="flex fd-col">
        <input type="hidden" name="letter_id" id="letter_id" value="{{pk}}">
        <p>Are you sure you want to delete the letter?</p>
        <br>
        <div class="buttons_cta">
            <a href="{% url 'index' %}" id="backbtn" class="button">Back</a>
            <a class="button" id="delete">Delete</a>
        </div>
    </div>
</section>

<script src="{% static 'js/delete_letter.js' %}"></script>

{% endblock content %}

mentors/templates/mentors/edit_letter.html
{% extends 'mentors/base.html' %}
{% load static %}
{% block title %}Edit Letter{% endblock title %}
{% block content %}

    <section class="cud_letter">
        <form id="editForm" action="" class="flex fd-col">
            <input type="hidden" name="letter_id" id="letter_id" value="{{letter.id}}">
            <div class="inputs flex fd-row">
                <label for="id_image" class="flex jc-fe">
                    <img src="{{letter.image.url}}" alt="letter_image"><i class="fas fa-plus-circle fa-3x"></i></i>
                    {{form.image}}
                </label>
                <div class="name_text flex fd-col ai-fs">
                    {{form.name}}
                    {{form.text}}
                </div>
            </div>
            <div class="buttons_cta">
                <a href="{% url 'index' %}" id="backbtn" class="button">Back</a>
                <input class="button" type="submit" value="Save Changes">
            </div>
        </form>
    </section>

    <script src="{% static 'js/edit_letter.js' %}"></script>

{% endblock content %}

mentors/templates/mentors/index.html
{% extends 'mentors/base.html' %}

{% load static %}
{% block title %}My Mentors{% endblock title %}

{% block content %}
    <div class="index">
        <h2>My Mentors</h2>
        <p>*A Thank You letter to my programming teachers.</p>
        <br>
        <div id="mentor_list" class="flex fd-col">
        </div>

        <br><br><br>

        <div class="letter">
            <h4>Your Thank You letter.</h4>
            <p>*Here you can leave your own Thank You letter to whomever you want.</p>
            <br>
            <div id="ty_letters" class="flex fd-col">
            </div>

            <div class="plus flex fd-row">
                <a href="{% url 'create_letter' %}"><i class="fas fa-plus fa-3x"></i></a>
            </div>
        </div>
    </div>

    <script src="{% static 'js/mymentor_ip.js' %}"></script>

{% endblock content %}

mentors/templates/mentors/mentor.html
{% extends 'mentors/base.html' %}
{% load static %}
{% block title %}{{mentor.mentor_name}}{% endblock title %}

{% block content %}

    <section class="mentor">
        <input type="hidden" name="pk_mentor" id="pk_mentor" value="{{mentor.id}}">
        <div style="max-width: 600px;" id="mentor_list" class="flex fd-col">
            <h2>Mentor</h2>

            <div id="card_text_container" class="card_text_container">
                <!-- Mentor's info goes here -->
            </div>

            <div id="course_container" class="course_container">
                <!-- All mentor's course goes here -->
            </div>

        </div>
    </section>

    <script src="{% static 'js/mentor_detail.js' %}"></script>

{% endblock content %}